[build-system]
requires = ["maturin>=1.8,<2"]
build-backend = "maturin"

[project]
name = "qayd"
version = "0.9.0"
description = "Yet another constraint-programming solver."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Rust",
  "Topic :: Scientific/Engineering :: Mathematics",
]
dependencies = [
    "vrplib>=1.3.0",
]

[tool.maturin]
features = ["python"]
module-name = "qayd._core"
python-source = "python"
