"""Type stubs for qayd, a constraint-programming solver (PyO3 extension).

These stubs mirror the ``qayd._core`` API defined in
``src/frontends/python.rs`` and re-exported by ``qayd/__init__.py``.
"""
from typing import Any, Callable, Dict, Iterable, Optional, Sequence, Tuple, Union, overload

__all__: list[str]

# --- operand type aliases -------------------------------------------------
# Anything an arithmetic operator / comparison accepts on an IntVar or Expr.
_IntoExpr = Union["IntVar", "Expr", int]
# Anything the boolean combinators (&, |, implies, iff, all, any) accept.
_IntoBool = Union["Constraint", "IntVar", "Expr"]
# A value inside a list-domain lambda body: another symbolic node or an int.
_LambdaLike = Union["LambdaExpr", int]
_Body1 = Callable[["LambdaExpr"], _LambdaLike]
_Body2 = Callable[["LambdaExpr", "LambdaExpr"], _LambdaLike]
_Body3 = Callable[["LambdaExpr", "LambdaExpr", "LambdaExpr"], _LambdaLike]
_Body4 = Callable[["LambdaExpr", "LambdaExpr", "LambdaExpr", "LambdaExpr"], _LambdaLike]
# An assumption item accepted by solve(assumptions=...) / session.solve(...).
_Assumption = Union["Constraint", "IntVar", Tuple["IntVar", int], Tuple["IntVar", str, int]]
_Incumbent = Callable[[int, Dict[int, int]], Any]
_AnytimeCheckpoint = Tuple[int, int, bool, list[int], Optional[int], int]
_NeighborhoodProfile = Tuple[str, int, int, int, int, int, int, int, float]
_RoutingCounter = Tuple[str, int]

# A relation string such as "==", "!=", "<=", "<", ">=", ">".
STAR: int


# ===========================================================================
# Decision-variable and expression handles
# ===========================================================================
class IntVar:
    """An integer decision variable handle bound to its owning Model."""

    @property
    def index(self) -> int: ...
    @property
    def name(self) -> Optional[str]: ...
    def expr(self) -> Expr: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __neg__(self) -> Expr: ...
    def __abs__(self) -> Expr: ...
    def __add__(self, rhs: _IntoExpr) -> Expr: ...
    def __radd__(self, lhs: _IntoExpr) -> Expr: ...
    def __sub__(self, rhs: _IntoExpr) -> Expr: ...
    def __rsub__(self, lhs: _IntoExpr) -> Expr: ...
    def __mul__(self, rhs: _IntoExpr) -> Expr: ...
    def __rmul__(self, lhs: _IntoExpr) -> Expr: ...
    def __floordiv__(self, rhs: _IntoExpr) -> Expr: ...
    def __rfloordiv__(self, lhs: _IntoExpr) -> Expr: ...
    def __mod__(self, rhs: _IntoExpr) -> Expr: ...
    def __rmod__(self, lhs: _IntoExpr) -> Expr: ...
    def __lt__(self, rhs: _IntoExpr) -> Constraint: ...
    def __le__(self, rhs: _IntoExpr) -> Constraint: ...
    def __gt__(self, rhs: _IntoExpr) -> Constraint: ...
    def __ge__(self, rhs: _IntoExpr) -> Constraint: ...
    def __eq__(self, rhs: _IntoExpr) -> Constraint: ...  # type: ignore[override]
    def __ne__(self, rhs: _IntoExpr) -> Constraint: ...  # type: ignore[override]
    def __hash__(self) -> int: ...


class Expr:
    """A symbolic arithmetic expression over model variables."""

    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __neg__(self) -> Expr: ...
    def __abs__(self) -> Expr: ...
    def __add__(self, rhs: _IntoExpr) -> Expr: ...
    def __radd__(self, lhs: _IntoExpr) -> Expr: ...
    def __sub__(self, rhs: _IntoExpr) -> Expr: ...
    def __rsub__(self, lhs: _IntoExpr) -> Expr: ...
    def __mul__(self, rhs: _IntoExpr) -> Expr: ...
    def __rmul__(self, lhs: _IntoExpr) -> Expr: ...
    def __floordiv__(self, rhs: _IntoExpr) -> Expr: ...
    def __rfloordiv__(self, lhs: _IntoExpr) -> Expr: ...
    def __mod__(self, rhs: _IntoExpr) -> Expr: ...
    def __rmod__(self, lhs: _IntoExpr) -> Expr: ...
    def __lt__(self, rhs: _IntoExpr) -> Constraint: ...
    def __le__(self, rhs: _IntoExpr) -> Constraint: ...
    def __gt__(self, rhs: _IntoExpr) -> Constraint: ...
    def __ge__(self, rhs: _IntoExpr) -> Constraint: ...
    def __eq__(self, rhs: _IntoExpr) -> Constraint: ...  # type: ignore[override]
    def __ne__(self, rhs: _IntoExpr) -> Constraint: ...  # type: ignore[override]
    def __hash__(self) -> int: ...


class Constraint:
    """A boolean constraint, built by comparing/combining expressions."""

    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __invert__(self) -> Constraint: ...
    def __and__(self, rhs: _IntoBool) -> Constraint: ...
    def __or__(self, rhs: _IntoBool) -> Constraint: ...
    def implies(self, rhs: _IntoBool) -> Constraint: ...
    def iff(self, rhs: _IntoBool) -> Constraint: ...


class ListVar:
    """An ordered list or unordered set handle from Model.list_vars()/set_vars()."""

    @property
    def index(self) -> int: ...
    def __repr__(self) -> str: ...


class IntervalVar:
    """An interval (scheduling) decision-variable handle."""

    @property
    def index(self) -> Optional[int]:
        """Backing native-interval index; ``None`` for a moded master."""
        ...
    @property
    def start(self) -> Optional[IntVar]: ...
    @property
    def presence(self) -> Optional[IntVar]: ...
    @property
    def optional(self) -> bool: ...
    @property
    def duration(self) -> Optional[int]: ...
    @property
    def end(self) -> Expr:
        """``start + duration``; for an alternative master, ``start + realized_duration``."""
        ...
    @property
    def realized_duration(self) -> Expr:
        """``Σ p_m·d_m`` of an alternative master; raises otherwise."""
        ...
    @property
    def members(self) -> list[IntervalVar]:
        """Member intervals of an alternative master (empty otherwise)."""
        ...
    def __repr__(self) -> str: ...


class SequenceVar:
    """A native interval sequence with sequence-dependent setup times."""

    @property
    def index(self) -> int: ...
    @property
    def intervals(self) -> list[IntervalVar]: ...
    def order(self, solution: "Solution") -> list[IntervalVar]: ...
    def __repr__(self) -> str: ...


# ===========================================================================
# List-domain (collection) modeling helpers
# ===========================================================================
class LambdaExpr:
    """A symbolic node in a list-domain lambda body."""

    def __add__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __radd__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __sub__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __rsub__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __mul__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __rmul__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __mod__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __rmod__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __pow__(self, exponent: int, modulo: None = ...) -> LambdaExpr: ...
    def __neg__(self) -> LambdaExpr: ...
    def __floordiv__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __rfloordiv__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __lt__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __le__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __gt__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __ge__(self, other: _LambdaLike) -> LambdaExpr: ...


class Array:
    """A constant integer array; index it with a lambda arg to read array[i]."""

    def __getitem__(self, idx: _LambdaLike) -> LambdaExpr: ...
    def __len__(self) -> int: ...


class Matrix:
    """A constant integer matrix; matrix[i][j] reads a cell."""

    def __getitem__(self, row: _LambdaLike) -> MatrixRow: ...


class MatrixRow:
    """The partially indexed matrix[i]; index again for matrix[i][j]."""

    def __getitem__(self, col: _LambdaLike) -> LambdaExpr: ...


class Term:
    """A term over one or more list variables."""

    def __add__(self, other: Term) -> Term: ...
    def __radd__(self, other: int) -> Term: ...
    def __mul__(self, other: int) -> Term: ...
    def __rmul__(self, other: int) -> Term: ...
    def __neg__(self) -> Term: ...
    def __le__(self, other: int | ListValue) -> ListConstraint | Reified: ...
    def __ge__(self, other: int | ListValue) -> ListConstraint | Reified: ...
    def __eq__(self, other: int | ListValue) -> ListConstraint | Reified: ...  # type: ignore[override]
    def __hash__(self) -> int: ...


class ListConstraint:
    """A constraint ``term <op> rhs`` over a single list reduction."""


class ListValue:
    """A collection-scoped scalar minted by ``Model.list_value()``; bind a scan
    total to it with ``add(scan == v)``, then use it in a linear objective."""

    def __add__(self, other: Term | ListValue) -> Term: ...
    def __radd__(self, other: Term | int) -> Term: ...
    def __mul__(self, other: int) -> Term: ...
    def __rmul__(self, other: int) -> Term: ...
    def __neg__(self) -> Term: ...


class Reified:
    """A reified binding ``scan == list_value``, recorded by ``Model.add``."""


class ScanResourceConstraint:
    """A constraint over a deterministic resource scan."""


class ScanResourcePointExpr:
    """A named resource view at one list item."""

    def __le__(self, rhs: int) -> ScanResourceConstraint: ...
    def __ge__(self, rhs: int) -> ScanResourceConstraint: ...
    def __eq__(self, rhs: object) -> ScanResourceConstraint: ...  # type: ignore[override]
    def __hash__(self) -> int: ...


class ScanResource:
    """A deterministic state threaded along one list variable."""

    def view(self, name: str, projection: _Body3) -> ScanResource: ...
    def at(self, item: int, *, view: str = ...) -> ScanResourcePointExpr: ...
    def after(self, item: int) -> ScanResourcePointExpr: ...
    def before(self, item: int) -> ScanResourcePointExpr: ...
    def within_bounds(
        self,
        *,
        view: str = ...,
        lower: Optional[int] = ...,
        upper: Optional[int] = ...,
    ) -> ScanResourceConstraint: ...


# ===========================================================================
# Routing convenience API
# ===========================================================================
class CustomerValue:
    """A scalar integer value attached to one customer."""

    customer: "CustomerRef"
    name: str
    value: int
    def __int__(self) -> int: ...


class CustomerRef:
    """One item in a routing model."""

    id: int
    def __getattr__(self, name: str) -> CustomerValue: ...
    def __setattr__(self, name: str, value: int) -> None: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...


class CustomerData:
    """A named dense value table over customers."""

    name: str
    def __getitem__(self, customer: Union[int, CustomerRef]) -> int: ...
    def array(self, *, default: int = ...) -> Array: ...
    def __repr__(self) -> str: ...


class CustomerSet:
    """Ordered customer ids plus per-customer data."""

    ids: list[int]
    def __iter__(self) -> Iterable[CustomerRef]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: Union[int, CustomerRef]) -> CustomerRef: ...
    def attr(self, name: str, values: Union[Sequence[int], Dict[int, int]]) -> CustomerData: ...
    def sum(self, fn: Callable[[CustomerRef], Any]) -> Any: ...
    def __repr__(self) -> str: ...


class VisitConstraint:
    """A constraint over a per-customer route visit view."""


class VisitStateExpr:
    """A per-customer state view, such as start time or load after service."""

    def __le__(self, rhs: Union[int, CustomerValue]) -> VisitConstraint: ...
    def __ge__(self, rhs: Union[int, CustomerValue]) -> VisitConstraint: ...
    def __eq__(self, rhs: Union[int, CustomerValue]) -> VisitConstraint: ...  # type: ignore[override]
    def __hash__(self) -> int: ...


class VisitRouteExpr:
    """The selected route of one customer."""

    def __eq__(self, other: "VisitRouteExpr") -> VisitConstraint: ...  # type: ignore[override]
    def __hash__(self) -> int: ...


class VisitPositionExpr:
    """The position of one customer in its route."""

    def __lt__(self, other: "VisitPositionExpr") -> VisitConstraint: ...
    def __hash__(self) -> int: ...


class VisitView:
    """Per-customer view induced by a RouteSet."""

    @property
    def start(self) -> VisitStateExpr: ...
    @property
    def load_after(self) -> VisitStateExpr: ...
    @property
    def route(self) -> VisitRouteExpr: ...
    @property
    def position(self) -> VisitPositionExpr: ...
    def same_route(self, other: "VisitView") -> VisitConstraint: ...
    def before(self, other: "VisitView") -> VisitConstraint: ...
    def __getattr__(self, name: str) -> "RouteResourceVisitView": ...
    def __repr__(self) -> str: ...


class RouteVar:
    """One visible route."""

    index: int
    def used(self) -> Term: ...
    def count(self) -> Term: ...
    def sum(self, fn: Callable[[CustomerRef], Any]) -> Term: ...
    def distance(self, travel: Optional[Any] = ...) -> Term: ...
    def load(self, demand: Optional[Any] = ...) -> Term: ...
    def profit(self, profit: Optional[Any] = ...) -> Term: ...
    def __repr__(self) -> str: ...


class RoutingResource:
    """One named deterministic resource over every route."""

    name: str
    def visit(self, customer: Union[int, CustomerRef]) -> "RouteResourceVisitView": ...
    def within_bounds(
        self,
        *,
        view: str = ...,
        lower: Optional[int] = ...,
        upper: Optional[int] = ...,
    ) -> VisitConstraint: ...
    def __repr__(self) -> str: ...


class RouteResourceVisitView:
    """Per-customer view of one route resource."""

    @property
    def before(self) -> "RouteResourcePointExpr": ...
    @property
    def after(self) -> "RouteResourcePointExpr": ...


class RouteResourcePointExpr:
    """A route resource view for one customer."""

    def __le__(self, rhs: Union[int, CustomerValue]) -> VisitConstraint: ...
    def __ge__(self, rhs: Union[int, CustomerValue]) -> VisitConstraint: ...
    def __eq__(self, rhs: Union[int, CustomerValue]) -> VisitConstraint: ...  # type: ignore[override]
    def __hash__(self) -> int: ...


class RouteSet:
    """A set of visible routes over a customer set."""

    customers: CustomerSet
    depot: int
    optional: bool
    def __iter__(self) -> Iterable[RouteVar]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, customer: Union[int, CustomerRef]) -> VisitView: ...
    def sum(self, fn: Callable[[RouteVar], Term]) -> Term: ...
    def used_count(self) -> Term: ...
    def total_distance(self, travel: Optional[Any] = ...) -> Term: ...
    def total_profit(self, profit: Optional[Any] = ...) -> Term: ...
    def resource(
        self,
        name: str,
        *,
        initial: int = ...,
        lower: Optional[int] = ...,
        upper: Optional[int] = ...,
        bounds: Optional[Tuple[int, int]] = ...,
        delta: Optional[Callable[[Any, Any], Any]] = ...,
        transition: Optional[Callable[[Any, Any, Any], Any]] = ...,
        consume: Optional[Callable[[Any, Any], Any]] = ...,
        produce: Optional[Callable[[Any], Any]] = ...,
        refill: Optional[Callable[[Any], Any]] = ...,
    ) -> RoutingResource: ...
    def __repr__(self) -> str: ...


# ===========================================================================
# Scheduling convenience API
# ===========================================================================
class TaskValue:
    """A value attached to one task."""

    task: "TaskRef"
    name: str
    value: Any
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...


class TaskRef:
    """One task in a scheduling model."""

    id: int
    def __getattr__(self, name: str) -> TaskValue: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...


class TaskData:
    """A named value table over tasks."""

    name: str
    def __getitem__(self, task: Union[int, TaskRef]) -> Any: ...
    def __repr__(self) -> str: ...


class TaskSet:
    """Ordered task ids plus per-task data."""

    ids: list[int]
    def __iter__(self) -> Iterable[TaskRef]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: Union[int, TaskRef]) -> TaskRef: ...
    def attr(self, name: str, values: Union[Sequence[Any], Dict[int, Any]]) -> TaskData: ...
    def group_by(self, fn_or_attr: Union[str, Callable[[TaskRef], Any]]) -> Dict[Any, list[TaskRef]]: ...
    def sum(self, fn: Callable[[TaskRef], Any]) -> Any: ...
    def __repr__(self) -> str: ...


class ScheduleConstraint:
    """A constraint over a task schedule."""


class TaskEndpointExpr:
    """A scheduled task endpoint, such as start or end."""

    def __le__(self, rhs: Any) -> ScheduleConstraint: ...
    def __ge__(self, rhs: Any) -> ScheduleConstraint: ...
    def __eq__(self, rhs: object) -> ScheduleConstraint: ...  # type: ignore[override]
    def __hash__(self) -> int: ...


class ScheduledTaskView:
    """Decision view of one task in a schedule."""

    task: TaskRef
    @property
    def interval(self) -> IntervalVar: ...
    @property
    def start(self) -> TaskEndpointExpr: ...
    @property
    def end(self) -> TaskEndpointExpr: ...
    @property
    def presence(self) -> Optional[IntVar]: ...
    def before(self, other: "ScheduledTaskView") -> ScheduleConstraint: ...
    def __repr__(self) -> str: ...


class ScheduleResourceExpr:
    """Renewable resource usage induced by overlapping scheduled tasks."""

    def __le__(self, capacity: Any) -> ScheduleConstraint: ...
    def __ge__(self, capacity: Any) -> ScheduleConstraint: ...
    def __eq__(self, capacity: object) -> ScheduleConstraint: ...  # type: ignore[override]
    def __hash__(self) -> int: ...


class ScheduleMakespanObjective:
    """Objective handle consumed by ``model.minimize``."""


class ScheduleSet:
    """A set of scheduled tasks over interval variables."""

    tasks: TaskSet
    horizon: int
    optional: bool
    moded: bool
    def __iter__(self) -> Iterable[ScheduledTaskView]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, task: Union[int, TaskRef]) -> ScheduledTaskView: ...
    def intervals(self, tasks: Optional[Iterable[Union[int, TaskRef]]] = ...) -> list[IntervalVar]: ...
    def resource(self, amount: Callable[[TaskRef], Any]) -> ScheduleResourceExpr: ...
    def no_overlap(self, key: Optional[Callable[[TaskRef], Any]] = ...) -> ScheduleConstraint: ...
    def makespan(self) -> ScheduleMakespanObjective: ...
    def __repr__(self) -> str: ...


# ===========================================================================
# Results
# ===========================================================================
class SolveStats:
    """Search statistics returned on a Solution."""

    @property
    def solutions(self) -> int: ...
    @property
    def nodes(self) -> int: ...
    @property
    def failures(self) -> int: ...
    @property
    def lcg_atoms(self) -> int: ...
    @property
    def propagator_calls(self) -> int: ...
    @property
    def learned_lits(self) -> int: ...
    @property
    def vivified_clauses(self) -> int: ...
    @property
    def vivified_lits(self) -> int: ...
    @property
    def lp_rows(self) -> int: ...
    @property
    def lp_model_status(self) -> str: ...
    @property
    def lp_variables(self) -> int: ...
    @property
    def lp_columns(self) -> int: ...
    @property
    def lp_covered_variables(self) -> int: ...
    @property
    def lp_objective_variables(self) -> int: ...
    @property
    def lp_objective_covered_variables(self) -> int: ...
    @property
    def lp_auxiliary_columns(self) -> int: ...
    @property
    def lp_objective_fallbacks(self) -> int: ...
    @property
    def lp_source_rows(self) -> int: ...
    @property
    def lp_nonzeros(self) -> int: ...
    @property
    def lp_solves(self) -> int: ...
    @property
    def lp_certified(self) -> int: ...
    @property
    def lp_route_ng_size(self) -> int: ...
    @property
    def lp_timeouts(self) -> int: ...
    @property
    def lp_refactorizations(self) -> int: ...
    @property
    def lp_micros(self) -> int: ...
    @property
    def lp_root_bound(self) -> Optional[int]: ...
    @property
    def lp_node_prunes(self) -> int: ...
    def __repr__(self) -> str: ...


class MusEnumeration:
    """Result of `Model.enumerate_mus`: minimal unsatisfiable subsets, minimal
    satisfiable subsets, and whether enumeration ran to completion."""

    @property
    def muses(self) -> list[list[str]]: ...
    @property
    def msses(self) -> list[list[str]]: ...
    @property
    def complete(self) -> bool: ...
    def __repr__(self) -> str: ...


class Solution:
    """The outcome of a solve: status, objective, and variable values."""

    @property
    def status(self) -> str: ...
    @property
    def values(self) -> list[Optional[int]]: ...
    @property
    def objective(self) -> Optional[int]: ...
    @property
    def dual_bound(self) -> Optional[int]: ...
    @property
    def absolute_gap(self) -> Optional[int]: ...
    @property
    def relative_gap(self) -> Optional[float]: ...
    @property
    def bound_method(self) -> Optional[str]: ...
    @property
    def alns_iterations(self) -> Optional[int]: ...
    @property
    def candidates_evaluated(self) -> Optional[int]: ...
    @property
    def candidates_per_second(self) -> Optional[float]: ...
    @property
    def schedule_moves_considered(self) -> Optional[int]: ...
    @property
    def schedule_moves_accepted(self) -> Optional[int]: ...
    @property
    def schedule_moves_rejected(self) -> Optional[int]: ...
    @property
    def schedule_work_steps(self) -> Optional[int]: ...
    @property
    def schedule_local_improvements(self) -> Optional[int]: ...
    @property
    def schedule_global_improvements(self) -> Optional[int]: ...
    @property
    def schedule_progress_publications(self) -> Optional[int]: ...
    @property
    def schedule_incumbent_publication_attempts(self) -> Optional[int]: ...
    @property
    def schedule_incumbent_publications(self) -> Optional[int]: ...
    @property
    def schedule_incumbent_injection_attempts(self) -> Optional[int]: ...
    @property
    def schedule_incumbent_injections(self) -> Optional[int]: ...
    @property
    def schedule_incumbent_rejections(self) -> Optional[int]: ...
    @property
    def schedule_incumbent_verifications(self) -> Optional[int]: ...
    @property
    def schedule_incumbent_verification_rejections(self) -> Optional[int]: ...
    @property
    def schedule_incumbent_verification_interruptions(self) -> Optional[int]: ...
    @property
    def schedule_incumbent_incomplete_rejections(self) -> Optional[int]: ...
    @property
    def schedule_restart_boundaries(self) -> Optional[int]: ...
    @property
    def schedule_peak_buffered_candidates(self) -> Optional[int]: ...
    @property
    def schedule_stalled_workers(self) -> Optional[int]: ...
    @property
    def schedule_stalled_unused_work_steps(self) -> Optional[int]: ...
    @property
    def schedule_worker_work_min(self) -> Optional[int]: ...
    @property
    def schedule_worker_work_max(self) -> Optional[int]: ...
    @property
    def schedule_work_budget_overruns(self) -> Optional[int]: ...
    @property
    def schedule_elite_pool_size(self) -> Optional[int]: ...
    @property
    def schedule_unused_work_steps(self) -> Optional[int]: ...
    @property
    def schedule_incumbent_source_worker(self) -> Optional[int]: ...
    @property
    def schedule_incumbent_source_round(self) -> Optional[int]: ...
    @property
    def schedule_cycle_rejections(self) -> Optional[int]: ...
    @property
    def schedule_reconstructions(self) -> Optional[int]: ...
    @property
    def critical_path_updates(self) -> Optional[int]: ...
    @property
    def schedule_window_rejections(self) -> Optional[int]: ...
    @property
    def schedule_objective_rejections(self) -> Optional[int]: ...
    @property
    def resource_profile_checks(self) -> Optional[int]: ...
    @property
    def resource_candidate_scheduling_attempts(self) -> Optional[int]: ...
    @property
    def resource_event_visits(self) -> Optional[int]: ...
    @property
    def resource_peak_profile_events(self) -> Optional[int]: ...
    @property
    def schedule_precedence_rejections(self) -> Optional[int]: ...
    @property
    def schedule_infeasible_rejections(self) -> Optional[int]: ...
    @property
    def schedule_justification_attempts(self) -> Optional[int]: ...
    @property
    def schedule_delta_evaluations(self) -> Optional[int]: ...
    @property
    def schedule_full_evaluations(self) -> Optional[int]: ...
    @property
    def schedule_full_fallbacks(self) -> Optional[int]: ...
    @property
    def schedule_topological_rebuilds(self) -> Optional[int]: ...
    @property
    def schedule_oracle_validations(self) -> Optional[int]: ...
    @property
    def schedule_oracle_mismatches(self) -> Optional[int]: ...
    @property
    def schedule_dirty_cone_operations(self) -> Optional[int]: ...
    @property
    def schedule_max_dirty_cone(self) -> Optional[int]: ...
    @property
    def schedule_workspace_growths(self) -> Optional[int]: ...
    @property
    def schedule_workspace_rollbacks(self) -> Optional[int]: ...
    @property
    def schedule_alns_generation_attempts(self) -> Optional[int]: ...
    @property
    def schedule_alns_moves_generated(self) -> Optional[int]: ...
    @property
    def full_recompute_percentage(self) -> Optional[float]: ...
    @property
    def backend_build_seconds(self) -> Optional[float]: ...
    @property
    def construction_seconds(self) -> Optional[float]: ...
    @property
    def time_to_first_feasible(self) -> Optional[float]: ...
    @property
    def construction_candidates(self) -> Optional[int]: ...
    @property
    def estimated_backend_bytes(self) -> Optional[int]: ...
    @property
    def constructor(self) -> Optional[str]: ...
    @property
    def constructor_fleet(self) -> Optional[int]: ...
    @property
    def constructor_cost(self) -> Optional[int]: ...
    @property
    def anytime_checkpoints(self) -> Optional[list[_AnytimeCheckpoint]]: ...
    @property
    def neighborhood_profile(self) -> Optional[list[_NeighborhoodProfile]]: ...
    @property
    def routing_counters(self) -> Optional[list[_RoutingCounter]]: ...
    @property
    def ls_moves(self) -> Optional[int]: ...
    @property
    def ls_constraints(self) -> Optional[int]: ...
    @property
    def ls_functionals(self) -> Optional[int]: ...
    @property
    def ls_unsupported(self) -> Optional[int]: ...
    @property
    def ls_rejected_incumbents(self) -> Optional[int]: ...
    @property
    def ls_checkpoint_replays(self) -> Optional[int]: ...
    @property
    def objectives(self) -> list[int]: ...
    @property
    def starts(self) -> list[Optional[int]]: ...
    @property
    def presences(self) -> list[bool]: ...
    @property
    def machines(self) -> list[int]: ...
    @property
    def objective_sense(self) -> Optional[str]: ...
    @property
    def objective_expr(self) -> Optional[str]: ...
    @property
    def lists(self) -> Optional[list[list[int]]]: ...
    @property
    def stats(self) -> SolveStats: ...
    def is_sat(self) -> bool: ...
    def value(self, var: IntVar) -> int: ...
    def assignment(self) -> Dict[int, int]: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...


class SolveSession:
    """An incremental solve session that retains learned nogoods across solves."""

    @property
    def learned_nogoods(self) -> int: ...
    def clear_nogoods(self) -> None: ...
    def raw_nogoods(self, limit: Optional[int] = ...) -> list[Tuple[int, list[int]]]: ...
    def nogoods(self, limit: Optional[int] = ...) -> list[Tuple[int, list[Tuple[int, str, int]]]]: ...
    def solve(
        self,
        *,
        search: Optional[Iterable[IntVar]] = ...,
        assumptions: Optional[Iterable[_Assumption]] = ...,
        hints: Optional[Iterable[Tuple[IntVar, int]]] = ...,
        branch_order: Optional[Iterable[IntVar]] = ...,
        on_incumbent: Optional[_Incumbent] = ...,
        verbose: bool = ...,
        time_limit: Optional[int] = ...,
        seed: int = ...,
        conflict_budget: Optional[int] = ...,
        linear_backend: str = ...,
        lp_root_ms: int = ...,
        lp_node_ms: int = ...,
        lp_node_depth_interval: int = ...,
        lp_max_variables: int = ...,
        lp_max_rows: int = ...,
        lp_max_nonzeros: int = ...,
        lp_min_coverage_percent: int = ...,
        lp_phase_max_variables: int = ...,
        lp_route_ng_size: int = ...,
        lp_route_max_labels: int = ...,
        lp_route_dual_stabilization_percent: int = ...,
    ) -> Solution: ...
    def __repr__(self) -> str: ...


# ===========================================================================
# Model
# ===========================================================================
class Model:
    """A constraint-programming model: declare variables, post constraints, solve."""

    def __init__(self) -> None: ...
    @property
    def num_vars(self) -> int: ...
    @property
    def num_constraints(self) -> int: ...
    @property
    def objective_sense(self) -> Optional[str]: ...
    @property
    def objective_expr(self) -> Optional[str]: ...

    # --- variable creation ---
    def int_var(
        self,
        lo: Optional[int] = ...,
        hi: Optional[int] = ...,
        *,
        values: Optional[Sequence[int]] = ...,
        name: Optional[str] = ...,
    ) -> IntVar: ...
    def bool_var(self, name: Optional[str] = ...) -> IntVar: ...
    def int_vars(self, n: int, lo: int, hi: int, *, name: Optional[str] = ...) -> list[IntVar]: ...
    def variables(self) -> list[IntVar]: ...
    def customers(self, items: Iterable[int]) -> CustomerSet: ...
    def routes(
        self,
        customers: Union[CustomerSet, Iterable[int]],
        *,
        vehicles: int,
        depot: int = ...,
        travel: Optional[Any] = ...,
        optional: bool = ...,
    ) -> RouteSet: ...
    def tasks(self, items: Iterable[int]) -> TaskSet: ...
    def schedule(
        self,
        tasks: Union[TaskSet, Iterable[int]],
        *,
        horizon: int,
        optional: bool = ...,
    ) -> ScheduleSet: ...

    # --- posting constraints ---
    def add(
        self,
        constraint: Union[
            Constraint,
            ListConstraint,
            ScanResourceConstraint,
            VisitConstraint,
            ScheduleConstraint,
            Iterable[Union[Constraint, ListConstraint, ScanResourceConstraint, VisitConstraint, ScheduleConstraint]],
        ],
    ) -> None: ...
    def linear(self, coeffs: Sequence[int], vars: Iterable[IntVar], relation: str, rhs: int) -> None: ...
    def sum(self, vars: Iterable[IntVar], relation: str, rhs: int) -> None: ...
    def all_different(self, vars: Iterable[IntVar]) -> None: ...
    def all_equal(self, vars: Iterable[IntVar]) -> None: ...
    def not_equal(self, x: IntVar, y: IntVar) -> None: ...
    def not_equal_offset(self, x: IntVar, y: IntVar, offset: int = ...) -> None: ...
    def ordered(self, vars: Iterable[IntVar], relation: str) -> None: ...
    def instantiate(self, vars: Iterable[IntVar], values: Sequence[int]) -> None: ...
    def minimum(self, target: IntVar, vars: Iterable[IntVar]) -> None: ...
    def maximum(self, target: IntVar, vars: Iterable[IntVar]) -> None: ...
    def element(self, array: Iterable[IntVar], index: IntVar, value: IntVar) -> None: ...
    def element_const(self, array: Sequence[int], index: IntVar, value: IntVar) -> None: ...
    def count(self, vars: Iterable[IntVar], value: int, relation: str, k: int) -> None: ...
    def cardinality(
        self,
        vars: Iterable[IntVar],
        values: Sequence[int],
        low: Sequence[int],
        high: Sequence[int],
        *,
        closed: bool = ...,
    ) -> None: ...
    def n_values(self, vars: Iterable[IntVar], relation: str, k: int) -> None: ...
    def table(self, vars: Iterable[IntVar], tuples: Sequence[Sequence[int]], *, positive: bool = ...) -> None: ...
    def lex(self, x: Iterable[IntVar], y: Iterable[IntVar], *, strict: bool = ...) -> None: ...
    def lex_chain(self, rows: Iterable[Iterable[IntVar]], *, strict: bool = ...) -> None: ...
    def channel(self, x: Iterable[IntVar], y: Iterable[IntVar]) -> None: ...
    def no_overlap(
        self,
        items: Union[Iterable[IntVar], Iterable[IntervalVar]],
        durations: Optional[Sequence[int]] = ...,
    ) -> None: ...
    def sequence(self, items: Iterable[IntervalVar], transitions: Sequence[Sequence[int]]) -> SequenceVar: ...
    def cumulative(
        self, starts: Iterable[IntVar], durations: Sequence[int], heights: Sequence[int], capacity: int
    ) -> None: ...
    def cumulative_var(
        self,
        starts: Iterable[IntVar],
        durations: Iterable[IntVar],
        heights: Iterable[IntVar],
        capacity: IntVar,
    ) -> None: ...
    def bin_packing(self, items: Iterable[IntVar], sizes: Sequence[int], capacities: Sequence[int]) -> None: ...
    def knapsack(
        self,
        vars: Iterable[IntVar],
        weights: Sequence[int],
        profits: Sequence[int],
        weight_relation: str,
        weight_limit: int,
        profit_relation: str,
        profit_limit: int,
    ) -> None: ...
    def circuit(self, successors: Iterable[IntVar]) -> None: ...

    # --- list-domain (collection) modeling ---
    def list_vars(self, items: Sequence[int], count: int, *, optional: bool = ...) -> list[ListVar]: ...
    def set_vars(self, items: Sequence[int], count: int, *, optional: bool = ...) -> list[ListVar]: ...
    def list_value(self) -> ListValue: ...
    def precedence(self, before: Union[int, IntervalVar], after: Union[int, IntervalVar]) -> None: ...
    def same_list(self, a: int, b: int) -> None: ...
    def different_list(self, a: int, b: int) -> None: ...
    def all_same_list(self, items: Sequence[int]) -> None: ...
    def all_different_lists(self, items: Sequence[int]) -> None: ...
    def list_distance(self, a: int, b: int, *, min: int = ..., max: int = ...) -> None: ...

    # --- interval (scheduling) modeling ---
    def interval(self, duration: int, horizon: int, *, optional: bool = ..., name: Optional[str] = ...) -> IntervalVar: ...
    def intervals(
        self, durations: Sequence[int], horizon: int, *, optional: bool = ..., name: Optional[str] = ...
    ) -> list[IntervalVar]: ...
    def schedule_intervals(
        self, durations: Sequence[int], horizon: int, *, optional: bool = ...
    ) -> list[IntervalVar]: ...
    def alternatives(self, modes: Sequence[Sequence[Tuple[int, int]]], horizon: int) -> list[IntervalVar]: ...
    def alternative(
        self, members: Sequence[IntervalVar], *, optional: bool = ..., name: Optional[str] = ...
    ) -> IntervalVar:
        """One member executes while the master is present. An optional master
        and all of its members may be absent."""
        ...
    def no_overlap_by_machine(self) -> None: ...
    def minimize_makespan(self, intervals: Optional[Iterable[IntervalVar]] = ...) -> None: ...
    def resource(self, demands: Sequence[Tuple[IntervalVar, int]], capacity: int) -> None: ...
    def resource_calendar(
        self,
        demands: Sequence[Tuple[IntervalVar, int]],
        default_capacity: int,
        calendar: Sequence[Tuple[int, int, int]],
    ) -> None: ...
    def state_function(
        self,
        states: Sequence[Tuple[IntervalVar, int]],
        transitions: Sequence[Sequence[int]],
    ) -> None: ...

    # --- objectives ---
    def minimize(self, objective: Union[IntVar, Expr, Term, ScheduleMakespanObjective]) -> None: ...
    def maximize(self, objective: Union[IntVar, Expr, Term]) -> None: ...
    def then_minimize(self, objective: Union[IntVar, Expr, Term]) -> None: ...
    def then_maximize(self, objective: Union[IntVar, Expr, Term]) -> None: ...

    # --- solving ---
    def solve(
        self,
        *,
        search: Optional[Iterable[IntVar]] = ...,
        assumptions: Optional[Iterable[_Assumption]] = ...,
        hints: Optional[Iterable[Tuple[IntVar, int]]] = ...,
        branch_order: Optional[Iterable[IntVar]] = ...,
        on_incumbent: Optional[_Incumbent] = ...,
        verbose: bool = ...,
        time_limit: Optional[int] = ...,
        seed: int = ...,
        threads: int = ...,
        engine: str = ...,
        conflict_budget: Optional[int] = ...,
        list_hint: Optional[list[list[int]]] = ...,
        max_iterations: Optional[int] = ...,
        profile: bool = ...,
        memory_limit_mb: Optional[int] = ...,
        schedule_cdcl: bool = ...,
        routing_two_way: bool = ...,
        routing_nearest_neighbor: bool = ...,
        routing_warm_start: bool = ...,
        linear_backend: str = ...,
        lp_root_ms: int = ...,
        lp_node_ms: int = ...,
        lp_node_depth_interval: int = ...,
        lp_max_variables: int = ...,
        lp_max_rows: int = ...,
        lp_max_nonzeros: int = ...,
        lp_min_coverage_percent: int = ...,
        lp_phase_max_variables: int = ...,
        lp_route_ng_size: int = ...,
        lp_route_max_labels: int = ...,
        lp_route_dual_stabilization_percent: int = ...,
    ) -> Solution: ...
    def count_solutions(self, search: Optional[Iterable[IntVar]] = ...) -> int: ...
    def session(self) -> SolveSession: ...
    def __repr__(self) -> str: ...


# ===========================================================================
# Module-level functions
# ===========================================================================
def expr(value: _IntoExpr) -> Expr:
    """Wrap an IntVar or integer as an Expr."""
    ...


def all(items: Iterable[_IntoBool]) -> Constraint:
    """Conjunction of the given constraints/expressions."""
    ...


def any(items: Iterable[_IntoBool]) -> Constraint:
    """Disjunction of the given constraints/expressions."""
    ...


def implies(a: _IntoBool, b: _IntoBool) -> Constraint:
    """The implication ``a -> b``."""
    ...


def iff(a: _IntoBool, b: _IntoBool) -> Constraint:
    """The biconditional ``a <-> b``."""
    ...


def min_of(items: Iterable[_IntoExpr]) -> Expr:
    """The minimum of the given expressions."""
    ...


@overload
def max_of(items: Iterable[Term]) -> Term:
    """The maximum of the given list-domain terms."""
    ...


@overload
def max_of(items: Iterable[_IntoExpr]) -> Expr:
    """The maximum of the given expressions."""
    ...


def if_then_else(condition: _IntoExpr, then_expr: _IntoExpr, else_expr: _IntoExpr) -> Expr:
    """A conditional expression ``condition != 0 ? then_expr : else_expr``."""
    ...


def domain(values: Sequence[int]) -> list[int]:
    """Validate and return a list of domain values (checked to fit i32)."""
    ...


def array(data: Sequence[int]) -> Array:
    """Wrap a constant integer array for use inside list-domain lambdas."""
    ...


def matrix(data: Sequence[Sequence[int]]) -> Matrix:
    """Wrap a constant integer matrix for use inside list-domain lambdas."""
    ...


# sum() dispatches: a route + lambda or an iterable of Terms build a Term;
# an iterable of arithmetic operands (Expr/IntVar/int) builds an Expr.
@overload
def sum(arg: ListVar, func: _Body1) -> Term: ...
@overload
def sum(arg: Iterable[Term]) -> Term: ...
@overload
def sum(arg: Iterable[_IntoExpr]) -> Expr: ...


def minimum(route: ListVar, func: _Body1) -> Term:
    """``min(route, i => body)`` over a route's items."""
    ...


def maximum(route: ListVar, func: _Body1) -> Term:
    """``max(route, i => body)`` over a route's items."""
    ...


def count(route: ListVar, func: Optional[_Body1] = ...) -> Term:
    """Items whose body is non-zero; with no lambda, the route's length."""
    ...


def sum_edges(route: ListVar, func: _Body2, *, start: int = ..., end: int = ...) -> Term:
    """Sum ``body`` over the edges of the closed tour ``[start, items.., end]``."""
    ...


def item_pairs(route: ListVar, func: _Body2) -> Term:
    """Sum ``body`` over every ordered pair of items ``(a, b)`` in the route."""
    ...


def pos_pairs(route: ListVar, func: _Body4) -> Term:
    """Sum ``body`` over ordered position pairs, items a/b at positions i/j."""
    ...


def min(a: _LambdaLike, b: _LambdaLike) -> LambdaExpr:
    """``min(a, b)`` inside a list-domain lambda body."""
    ...


def max(a: _LambdaLike, b: _LambdaLike) -> LambdaExpr:
    """``max(a, b)`` inside a list-domain lambda body."""
    ...


def abs(a: _LambdaLike) -> LambdaExpr:
    """``abs(x)`` inside a list-domain lambda body."""
    ...


def if_(cond: _LambdaLike, a: _LambdaLike, b: _LambdaLike) -> LambdaExpr:
    """``cond != 0 ? a : b`` inside a list-domain lambda body."""
    ...


def eq(a: _LambdaLike, b: _LambdaLike) -> LambdaExpr:
    """``a == b`` (1 or 0) inside a list-domain lambda body."""
    ...


def ne(a: _LambdaLike, b: _LambdaLike) -> LambdaExpr:
    """``a != b`` (1 or 0) inside a list-domain lambda body."""
    ...


def fixed(value: float, *, scale: int = ...) -> int:
    """Convert a finite float to its deterministic fixed-point raw integer."""
    ...


def mul_scaled(a: _LambdaLike, b: _LambdaLike, scale: int) -> LambdaExpr:
    """Fixed-point multiplication ``round(a * b / scale)``."""
    ...


def div_scaled(a: _LambdaLike, b: _LambdaLike, scale: int) -> LambdaExpr:
    """Fixed-point division ``round(a * scale / b)``."""
    ...


def piecewise(input: _LambdaLike, points: Sequence[Tuple[int, int]]) -> LambdaExpr:
    """Continuous piecewise-linear interpolation over fixed-point knots."""
    ...


def register_external(name: str, function: Callable[..., int]) -> None:
    """Register a deterministic external callback under a process-global name."""
    ...


def external(name: str, *args: _LambdaLike) -> LambdaExpr:
    """Call a previously registered external function in a lambda body."""
    ...


def scan_sum(route: ListVar, step: _Body3, emit: _Body3, *, init: int = ..., boundary: int = ..., end: Optional[int] = ...) -> Term:
    """Fold an accumulator along the route and sum a per-step ``emit`` value."""
    ...


def scan_resource(
    route: ListVar,
    *,
    initial: int = ...,
    lower: Optional[int] = ...,
    upper: Optional[int] = ...,
    bounds: Optional[Tuple[int, int]] = ...,
    transition: Optional[_Body3] = ...,
    delta: Optional[_Body2] = ...,
    boundary: int = ...,
) -> ScanResource:
    """Thread one deterministic resource state along a list variable."""
    ...


def select_kth(
    route: ListVar, k: int, step: _Body3, emit: _Body3, *, init: int = ..., boundary: int = ...
) -> Term:
    """The k-th smallest per-step ``emit`` value along the route."""
    ...


def windows(route: ListVar, size: int, inner: _Body1, emit: _Body1) -> Term:
    """Sliding-window reduction: sum ``emit(total)`` over windows of ``size``."""
    ...


def used(route: ListVar) -> Term:
    """``1`` if the route has any item, else ``0`` (count of used routes/bins)."""
    ...
