"""Type stubs for qayd, a constraint-programming solver (PyO3 extension).

These stubs mirror the ``qayd._core`` API defined in
``src/frontends/python.rs`` and re-exported by ``qayd/__init__.py``.
"""
from typing import Any, Callable, Dict, Iterable, Optional, Sequence, Tuple, Union, overload

__all__: list[str]

# --- operand type aliases -------------------------------------------------
# Anything an arithmetic operator / comparison accepts on an IntVar or Expr.
_IntoExpr = Union["IntVar", "Expr", int]
# Anything the boolean combinators (&, |, implies, iff, all, any) accept.
_IntoBool = Union["Constraint", "IntVar", "Expr"]
# A value inside a list-domain lambda body: another symbolic node or an int.
_LambdaLike = Union["LambdaExpr", int]
_Body1 = Callable[["LambdaExpr"], _LambdaLike]
_Body2 = Callable[["LambdaExpr", "LambdaExpr"], _LambdaLike]
_Body3 = Callable[["LambdaExpr", "LambdaExpr", "LambdaExpr"], _LambdaLike]
_Body4 = Callable[["LambdaExpr", "LambdaExpr", "LambdaExpr", "LambdaExpr"], _LambdaLike]
# An assumption item accepted by solve(assumptions=...) / session.solve(...).
_Assumption = Union["Constraint", "IntVar", Tuple["IntVar", int], Tuple["IntVar", str, int]]
_Incumbent = Callable[[int, Dict[int, int]], Any]

# A relation string such as "==", "!=", "<=", "<", ">=", ">".
STAR: int


# ===========================================================================
# Decision-variable and expression handles
# ===========================================================================
class IntVar:
    """An integer decision variable handle bound to its owning Model."""

    @property
    def index(self) -> int: ...
    @property
    def name(self) -> Optional[str]: ...
    def expr(self) -> Expr: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __neg__(self) -> Expr: ...
    def __abs__(self) -> Expr: ...
    def __add__(self, rhs: _IntoExpr) -> Expr: ...
    def __radd__(self, lhs: _IntoExpr) -> Expr: ...
    def __sub__(self, rhs: _IntoExpr) -> Expr: ...
    def __rsub__(self, lhs: _IntoExpr) -> Expr: ...
    def __mul__(self, rhs: _IntoExpr) -> Expr: ...
    def __rmul__(self, lhs: _IntoExpr) -> Expr: ...
    def __floordiv__(self, rhs: _IntoExpr) -> Expr: ...
    def __rfloordiv__(self, lhs: _IntoExpr) -> Expr: ...
    def __mod__(self, rhs: _IntoExpr) -> Expr: ...
    def __rmod__(self, lhs: _IntoExpr) -> Expr: ...
    def __lt__(self, rhs: _IntoExpr) -> Constraint: ...
    def __le__(self, rhs: _IntoExpr) -> Constraint: ...
    def __gt__(self, rhs: _IntoExpr) -> Constraint: ...
    def __ge__(self, rhs: _IntoExpr) -> Constraint: ...
    def __eq__(self, rhs: _IntoExpr) -> Constraint: ...  # type: ignore[override]
    def __ne__(self, rhs: _IntoExpr) -> Constraint: ...  # type: ignore[override]
    def __hash__(self) -> int: ...


class Expr:
    """A symbolic arithmetic expression over model variables."""

    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __neg__(self) -> Expr: ...
    def __abs__(self) -> Expr: ...
    def __add__(self, rhs: _IntoExpr) -> Expr: ...
    def __radd__(self, lhs: _IntoExpr) -> Expr: ...
    def __sub__(self, rhs: _IntoExpr) -> Expr: ...
    def __rsub__(self, lhs: _IntoExpr) -> Expr: ...
    def __mul__(self, rhs: _IntoExpr) -> Expr: ...
    def __rmul__(self, lhs: _IntoExpr) -> Expr: ...
    def __floordiv__(self, rhs: _IntoExpr) -> Expr: ...
    def __rfloordiv__(self, lhs: _IntoExpr) -> Expr: ...
    def __mod__(self, rhs: _IntoExpr) -> Expr: ...
    def __rmod__(self, lhs: _IntoExpr) -> Expr: ...
    def __lt__(self, rhs: _IntoExpr) -> Constraint: ...
    def __le__(self, rhs: _IntoExpr) -> Constraint: ...
    def __gt__(self, rhs: _IntoExpr) -> Constraint: ...
    def __ge__(self, rhs: _IntoExpr) -> Constraint: ...
    def __eq__(self, rhs: _IntoExpr) -> Constraint: ...  # type: ignore[override]
    def __ne__(self, rhs: _IntoExpr) -> Constraint: ...  # type: ignore[override]
    def __hash__(self) -> int: ...


class Constraint:
    """A boolean constraint, built by comparing/combining expressions."""

    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __invert__(self) -> Constraint: ...
    def __and__(self, rhs: _IntoBool) -> Constraint: ...
    def __or__(self, rhs: _IntoBool) -> Constraint: ...
    def implies(self, rhs: _IntoBool) -> Constraint: ...
    def iff(self, rhs: _IntoBool) -> Constraint: ...


class ListVar:
    """A list (set) decision-variable handle from Model.list_vars()."""

    @property
    def index(self) -> int: ...
    def __repr__(self) -> str: ...


class IntervalVar:
    """An interval (scheduling) decision-variable handle."""

    @property
    def index(self) -> int: ...
    @property
    def start(self) -> Optional[IntVar]: ...
    @property
    def presence(self) -> Optional[IntVar]: ...
    @property
    def optional(self) -> bool: ...
    @property
    def duration(self) -> Optional[int]: ...
    @property
    def end(self) -> Expr:
        """``start + duration`` as an expression; raises for moded intervals."""
        ...
    def __repr__(self) -> str: ...


# ===========================================================================
# List-domain (collection) modeling helpers
# ===========================================================================
class LambdaExpr:
    """A symbolic node in a list-domain lambda body."""

    def __add__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __radd__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __sub__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __rsub__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __mul__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __rmul__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __neg__(self) -> LambdaExpr: ...
    def __floordiv__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __rfloordiv__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __lt__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __le__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __gt__(self, other: _LambdaLike) -> LambdaExpr: ...
    def __ge__(self, other: _LambdaLike) -> LambdaExpr: ...


class Array:
    """A constant integer array; index it with a lambda arg to read array[i]."""

    def __getitem__(self, idx: _LambdaLike) -> LambdaExpr: ...
    def __len__(self) -> int: ...


class Matrix:
    """A constant integer matrix; matrix[i][j] reads a cell."""

    def __getitem__(self, row: _LambdaLike) -> MatrixRow: ...


class MatrixRow:
    """The partially indexed matrix[i]; index again for matrix[i][j]."""

    def __getitem__(self, col: _LambdaLike) -> LambdaExpr: ...


class Term:
    """A term over one or more list variables: a sum of reductions."""

    def __add__(self, other: Term) -> Term: ...
    def __radd__(self, other: int) -> Term: ...
    def __le__(self, other: int) -> ListConstraint: ...
    def __ge__(self, other: int) -> ListConstraint: ...
    def __eq__(self, other: int) -> ListConstraint: ...  # type: ignore[override]
    def __hash__(self) -> int: ...


class ListConstraint:
    """A constraint ``term <op> rhs`` over a single list reduction."""


# ===========================================================================
# Results
# ===========================================================================
class SolveStats:
    """Search statistics returned on a Solution."""

    @property
    def solutions(self) -> int: ...
    @property
    def nodes(self) -> int: ...
    @property
    def failures(self) -> int: ...
    @property
    def learned_lits(self) -> int: ...
    @property
    def vivified_clauses(self) -> int: ...
    @property
    def vivified_lits(self) -> int: ...
    def __repr__(self) -> str: ...


class Solution:
    """The outcome of a solve: status, objective, and variable values."""

    @property
    def status(self) -> str: ...
    @property
    def objective(self) -> Optional[int]: ...
    @property
    def objectives(self) -> list[int]: ...
    @property
    def starts(self) -> list[Optional[int]]: ...
    @property
    def presences(self) -> list[bool]: ...
    @property
    def machines(self) -> list[int]: ...
    @property
    def objective_sense(self) -> Optional[str]: ...
    @property
    def objective_expr(self) -> Optional[str]: ...
    @property
    def lists(self) -> Optional[list[list[int]]]: ...
    @property
    def stats(self) -> SolveStats: ...
    def is_sat(self) -> bool: ...
    def value(self, var: IntVar) -> int: ...
    def assignment(self) -> Dict[int, int]: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...


class SolveSession:
    """An incremental solve session that retains learned nogoods across solves."""

    @property
    def learned_nogoods(self) -> int: ...
    def clear_nogoods(self) -> None: ...
    def raw_nogoods(self, limit: Optional[int] = ...) -> list[Tuple[int, list[int]]]: ...
    def nogoods(self, limit: Optional[int] = ...) -> list[Tuple[int, list[Tuple[int, str, int]]]]: ...
    def solve(
        self,
        *,
        search: Optional[Iterable[IntVar]] = ...,
        assumptions: Optional[Iterable[_Assumption]] = ...,
        hints: Optional[Iterable[Tuple[IntVar, int]]] = ...,
        branch_order: Optional[Iterable[IntVar]] = ...,
        on_incumbent: Optional[_Incumbent] = ...,
        verbose: bool = ...,
        time_limit: Optional[int] = ...,
        seed: int = ...,
        conflict_budget: Optional[int] = ...,
    ) -> Solution: ...
    def __repr__(self) -> str: ...


# ===========================================================================
# Model
# ===========================================================================
class Model:
    """A constraint-programming model: declare variables, post constraints, solve."""

    def __init__(self) -> None: ...
    @property
    def num_vars(self) -> int: ...
    @property
    def num_constraints(self) -> int: ...
    @property
    def objective_sense(self) -> Optional[str]: ...
    @property
    def objective_expr(self) -> Optional[str]: ...

    # --- variable creation ---
    def int_var(
        self,
        lo: Optional[int] = ...,
        hi: Optional[int] = ...,
        *,
        values: Optional[Sequence[int]] = ...,
        name: Optional[str] = ...,
    ) -> IntVar: ...
    def bool_var(self, name: Optional[str] = ...) -> IntVar: ...
    def int_vars(self, n: int, lo: int, hi: int, *, name: Optional[str] = ...) -> list[IntVar]: ...
    def variables(self) -> list[IntVar]: ...

    # --- posting constraints ---
    def add(self, constraint: Union[Constraint, ListConstraint, Iterable[Constraint]]) -> None: ...
    def linear(self, coeffs: Sequence[int], vars: Iterable[IntVar], relation: str, rhs: int) -> None: ...
    def sum(self, vars: Iterable[IntVar], relation: str, rhs: int) -> None: ...
    def all_different(self, vars: Iterable[IntVar]) -> None: ...
    def all_equal(self, vars: Iterable[IntVar]) -> None: ...
    def not_equal(self, x: IntVar, y: IntVar) -> None: ...
    def not_equal_offset(self, x: IntVar, y: IntVar, offset: int = ...) -> None: ...
    def ordered(self, vars: Iterable[IntVar], relation: str) -> None: ...
    def instantiate(self, vars: Iterable[IntVar], values: Sequence[int]) -> None: ...
    def minimum(self, target: IntVar, vars: Iterable[IntVar]) -> None: ...
    def maximum(self, target: IntVar, vars: Iterable[IntVar]) -> None: ...
    def element(self, array: Iterable[IntVar], index: IntVar, value: IntVar) -> None: ...
    def element_const(self, array: Sequence[int], index: IntVar, value: IntVar) -> None: ...
    def count(self, vars: Iterable[IntVar], value: int, relation: str, k: int) -> None: ...
    def cardinality(
        self,
        vars: Iterable[IntVar],
        values: Sequence[int],
        low: Sequence[int],
        high: Sequence[int],
        *,
        closed: bool = ...,
    ) -> None: ...
    def n_values(self, vars: Iterable[IntVar], relation: str, k: int) -> None: ...
    def table(self, vars: Iterable[IntVar], tuples: Sequence[Sequence[int]], *, positive: bool = ...) -> None: ...
    def lex(self, x: Iterable[IntVar], y: Iterable[IntVar], *, strict: bool = ...) -> None: ...
    def lex_chain(self, rows: Iterable[Iterable[IntVar]], *, strict: bool = ...) -> None: ...
    def channel(self, x: Iterable[IntVar], y: Iterable[IntVar]) -> None: ...
    def no_overlap(
        self,
        items: Union[Iterable[IntVar], Iterable[IntervalVar]],
        durations: Optional[Sequence[int]] = ...,
    ) -> None: ...
    def cumulative(
        self, starts: Iterable[IntVar], durations: Sequence[int], heights: Sequence[int], capacity: int
    ) -> None: ...
    def cumulative_var(
        self,
        starts: Iterable[IntVar],
        durations: Iterable[IntVar],
        heights: Iterable[IntVar],
        capacity: IntVar,
    ) -> None: ...
    def bin_packing(self, items: Iterable[IntVar], sizes: Sequence[int], capacities: Sequence[int]) -> None: ...
    def knapsack(
        self,
        vars: Iterable[IntVar],
        weights: Sequence[int],
        profits: Sequence[int],
        weight_relation: str,
        weight_limit: int,
        profit_relation: str,
        profit_limit: int,
    ) -> None: ...
    def circuit(self, successors: Iterable[IntVar]) -> None: ...

    # --- list-domain (collection) modeling ---
    def list_vars(self, items: Sequence[int], count: int, *, optional: bool = ...) -> list[ListVar]: ...
    def precedence(self, before: Union[int, IntervalVar], after: Union[int, IntervalVar]) -> None: ...
    def same_list(self, a: int, b: int) -> None: ...

    # --- interval (scheduling) modeling ---
    def interval(self, duration: int, horizon: int, *, optional: bool = ..., name: Optional[str] = ...) -> IntervalVar: ...
    def optional_interval(self, duration: int, horizon: int, *, name: Optional[str] = ...) -> IntervalVar: ...
    def intervals(
        self, durations: Sequence[int], horizon: int, *, optional: bool = ..., name: Optional[str] = ...
    ) -> list[IntervalVar]: ...
    def optional_intervals(
        self, durations: Sequence[int], horizon: int, *, name: Optional[str] = ...
    ) -> list[IntervalVar]: ...
    def alternatives(self, modes: Sequence[Sequence[Tuple[int, int]]], horizon: int) -> list[IntervalVar]: ...
    def no_overlap_by_machine(self) -> None: ...
    def minimize_makespan(self, intervals: Optional[Iterable[IntervalVar]] = ...) -> None: ...
    def resource(self, demands: Sequence[Tuple[IntervalVar, int]], capacity: int) -> None: ...

    # --- objectives ---
    def minimize(self, objective: Union[IntVar, Expr, Term]) -> None: ...
    def maximize(self, objective: Union[IntVar, Expr, Term]) -> None: ...
    def then_minimize(self, objective: Union[IntVar, Expr, Term]) -> None: ...
    def then_maximize(self, objective: Union[IntVar, Expr, Term]) -> None: ...

    # --- solving ---
    def solve(
        self,
        *,
        search: Optional[Iterable[IntVar]] = ...,
        assumptions: Optional[Iterable[_Assumption]] = ...,
        hints: Optional[Iterable[Tuple[IntVar, int]]] = ...,
        branch_order: Optional[Iterable[IntVar]] = ...,
        on_incumbent: Optional[_Incumbent] = ...,
        verbose: bool = ...,
        time_limit: Optional[int] = ...,
        seed: int = ...,
        engine: str = ...,
        conflict_budget: Optional[int] = ...,
    ) -> Solution: ...
    def count_solutions(self, search: Optional[Iterable[IntVar]] = ...) -> int: ...
    def session(self) -> SolveSession: ...
    def __repr__(self) -> str: ...


# ===========================================================================
# Module-level functions
# ===========================================================================
def expr(value: _IntoExpr) -> Expr:
    """Wrap an IntVar or integer as an Expr."""
    ...


def all(items: Iterable[_IntoBool]) -> Constraint:
    """Conjunction of the given constraints/expressions."""
    ...


def any(items: Iterable[_IntoBool]) -> Constraint:
    """Disjunction of the given constraints/expressions."""
    ...


def implies(a: _IntoBool, b: _IntoBool) -> Constraint:
    """The implication ``a -> b``."""
    ...


def iff(a: _IntoBool, b: _IntoBool) -> Constraint:
    """The biconditional ``a <-> b``."""
    ...


def min_of(items: Iterable[_IntoExpr]) -> Expr:
    """The minimum of the given expressions."""
    ...


def max_of(items: Iterable[_IntoExpr]) -> Expr:
    """The maximum of the given expressions."""
    ...


def if_then_else(condition: _IntoExpr, then_expr: _IntoExpr, else_expr: _IntoExpr) -> Expr:
    """A conditional expression ``condition != 0 ? then_expr : else_expr``."""
    ...


def domain(values: Sequence[int]) -> list[int]:
    """Validate and return a list of domain values (checked to fit i32)."""
    ...


def array(data: Sequence[int]) -> Array:
    """Wrap a constant integer array for use inside list-domain lambdas."""
    ...


def matrix(data: Sequence[Sequence[int]]) -> Matrix:
    """Wrap a constant integer matrix for use inside list-domain lambdas."""
    ...


# sum() dispatches: a route + lambda or an iterable of Terms build a Term;
# an iterable of arithmetic operands (Expr/IntVar/int) builds an Expr.
@overload
def sum(arg: ListVar, func: _Body1) -> Term: ...
@overload
def sum(arg: Iterable[Term]) -> Term: ...
@overload
def sum(arg: Iterable[_IntoExpr]) -> Expr: ...


def minimum(route: ListVar, func: _Body1) -> Term:
    """``min(route, i => body)`` over a route's items."""
    ...


def maximum(route: ListVar, func: _Body1) -> Term:
    """``max(route, i => body)`` over a route's items."""
    ...


def count(route: ListVar, func: Optional[_Body1] = ...) -> Term:
    """Items whose body is non-zero; with no lambda, the route's length."""
    ...


def sum_edges(route: ListVar, func: _Body2, *, start: int = ..., end: int = ...) -> Term:
    """Sum ``body`` over the edges of the closed tour ``[start, items.., end]``."""
    ...


def item_pairs(route: ListVar, func: _Body2) -> Term:
    """Sum ``body`` over every ordered pair of items ``(a, b)`` in the route."""
    ...


def pos_pairs(route: ListVar, func: _Body4) -> Term:
    """Sum ``body`` over ordered position pairs, items a/b at positions i/j."""
    ...


def min(a: _LambdaLike, b: _LambdaLike) -> LambdaExpr:
    """``min(a, b)`` inside a list-domain lambda body."""
    ...


def max(a: _LambdaLike, b: _LambdaLike) -> LambdaExpr:
    """``max(a, b)`` inside a list-domain lambda body."""
    ...


def abs(a: _LambdaLike) -> LambdaExpr:
    """``abs(x)`` inside a list-domain lambda body."""
    ...


def if_(cond: _LambdaLike, a: _LambdaLike, b: _LambdaLike) -> LambdaExpr:
    """``cond != 0 ? a : b`` inside a list-domain lambda body."""
    ...


def eq(a: _LambdaLike, b: _LambdaLike) -> LambdaExpr:
    """``a == b`` (1 or 0) inside a list-domain lambda body."""
    ...


def ne(a: _LambdaLike, b: _LambdaLike) -> LambdaExpr:
    """``a != b`` (1 or 0) inside a list-domain lambda body."""
    ...


def scan_sum(route: ListVar, step: _Body3, emit: _Body3, *, init: int = ..., boundary: int = ...) -> Term:
    """Fold an accumulator along the route and sum a per-step ``emit`` value."""
    ...


def select_kth(
    route: ListVar, k: int, step: _Body3, emit: _Body3, *, init: int = ..., boundary: int = ...
) -> Term:
    """The k-th smallest per-step ``emit`` value along the route."""
    ...


def windows(route: ListVar, size: int, inner: _Body1, emit: _Body1) -> Term:
    """Sliding-window reduction: sum ``emit(total)`` over windows of ``size``."""
    ...


def used(route: ListVar) -> Term:
    """``1`` if the route has any item, else ``0`` (count of used routes/bins)."""
    ...
