"""Python modeling interface for qayd."""

from ._core import (
    STAR,
    Constraint,
    Expr,
    IntVar,
    Model,
    Solution,
    SolveStats,
    abs,
    all,
    any,
    array,
    count,
    domain,
    eq,
    if_,
    expr,
    iff,
    if_then_else,
    implies,
    item_pairs,
    matrix,
    max,
    min,
    ne,
    pos_pairs,
    scan_sum,
    select_kth,
    max_of,
    maximum,
    min_of,
    minimum,
    sum,
    sum_edges,
    used,
    windows,
)
from .routing import (
    CustomerData,
    CustomerRef,
    CustomerSet,
    CustomerValue,
    RouteSet,
    RouteVar,
    VisitView,
    install_model_api as install_routing_api,
)

install_routing_api()

from .scheduling import (
    ScheduleSet,
    ScheduledTaskView,
    TaskData,
    TaskRef,
    TaskSet,
    TaskValue,
    install_model_api as install_scheduling_api,
)

install_scheduling_api()

__all__ = [
    "STAR",
    "Constraint",
    "CustomerData",
    "CustomerRef",
    "CustomerSet",
    "CustomerValue",
    "Expr",
    "IntVar",
    "Model",
    "RouteSet",
    "RouteVar",
    "ScheduleSet",
    "ScheduledTaskView",
    "Solution",
    "SolveStats",
    "TaskData",
    "TaskRef",
    "TaskSet",
    "TaskValue",
    "VisitView",
    "abs",
    "all",
    "any",
    "array",
    "count",
    "domain",
    "eq",
    "if_",
    "expr",
    "iff",
    "if_then_else",
    "implies",
    "item_pairs",
    "matrix",
    "max",
    "min",
    "ne",
    "pos_pairs",
    "scan_sum",
    "select_kth",
    "max_of",
    "maximum",
    "min_of",
    "minimum",
    "sum",
    "sum_edges",
    "used",
    "windows",
]
